<?php
/*
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Entity;

/**
 * This file has been generated by the Sonata product generation command ( http://sonata-project.org/ )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Travel extends Product
{
    /**
     * @var integer
     */
    protected $travellers;

    /**
     * @var \DateTime
     */
    protected $travelDate;

    /**
     * @var integer
     */
    protected $travelDays;

    /**
     * Sets travellers number
     *
     * @param int $travellers
     */
    public function setTravellers($travellers)
    {
        $this->travellers = $travellers;
    }

    /**
     * Returns travellers number
     *
     * @return int
     */
    public function getTravellers()
    {
        return $this->travellers;
    }

    /**
     * Sets travel date
     *
     * @param \DateTime $travelDate
     */
    public function setTravelDate($travelDate)
    {
        $this->travelDate = $travelDate;
    }

    /**
     * Returns travel date
     *
     * @return \DateTime
     */
    public function getTravelDate()
    {
        return $this->travelDate;
    }

    /**
     * Sets travel days number
     *
     * @param int $travelDays
     */
    public function setTravelDays($travelDays)
    {
        $this->travelDays = $travelDays;
    }

    /**
     * Returns travel days number
     *
     * @return int
     */
    public function getTravelDays()
    {
        return $this->travelDays;
    }
}
