<?php

declare(strict_types=1);

/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity\Comment;

use Sonata\CommentBundle\Entity\BaseComment as BaseComment;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends ).
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Comment extends BaseComment
{
    /**
     * @var int
     */
    protected $category;
    
    /**
     * @var int
     */
    protected $id;

    /**
     * @var UserInterface
     */
    protected $author;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * @return int
     */
    public function getCategory()
    {
        return $this->category;
    }
    
    /**
     * @param int $category
     */
    public function setCategory($category): void
    {
        $this->category = $category;
    }
}
