fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main

    # if you change the class configuration, please also alter the sonata_user.yml file
    user_class:        AppBundle\Entity\User\User

    group:
        group_class:   AppBundle\Entity\User\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    # This is required so I just copied from reference. TODO
    from_email:
        address:        webmaster@example.com
        sender_name:    Admin
