nelmio_api_doc:
  documentation:
    #host: api.example.com
    info:
      title: Sonata Sandbox
      description: This is demo RestFul API!
      version: 1.0.0

  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)
    #host_patterns:
     # - ^api\.
