sonata_basket:
    class:
        basket:         AppBundle\Entity\Commerce\Basket
        basket_element: AppBundle\Entity\Commerce\BasketElement
        customer:       AppBundle\Entity\Commerce\Customer

    builder:            sonata.basket.builder.standard
    factory:            sonata.basket.entity.factory
    loader:             sonata.basket.loader.standard

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataBasketBundle: ~
