# Enable Doctrine to map the provided entities
sonata_invoice:
    class:
        invoice:         App\Entity\Commerce\Invoice
        invoice_element: App\Entity\Commerce\InvoiceElement
        customer:        App\Entity\Commerce\Customer
        order_element:   App\Entity\Commerce\OrderElement

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataInvoiceBundle: ~
