#!/usr/bin/env php
<?php

require_once __DIR__.'/app/bootstrap.php.cache';
require_once __DIR__.'/app/AppKernel.php';

use Symfony\Component\Process\Process;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\ArgvInput;

// retrieve the application name
$output = new ConsoleOutput();

$validApp = array(
    'admin' => array('admin'),
    'front' => array('front'),
    'api'   => array('api'),
    'all'   => array('api', 'front', 'admin'),
);

$output->writeln("<info>The Sonata Project</info> - <comment>http://sonata-project.org</comment>");

if (count($_SERVER['argv']) < 2 || !isset($validApp[$_SERVER['argv'][1]])) {

    $output->writeln(<<<ERROR

<error>Error : please provide a valid application name</error>

./sonata <application_name> <symfony:command> <command_options>

ERROR
);

   exit(1);
}

$group = $_SERVER['argv'][1];

unset($_SERVER['argv'][1]);

$args = new ArgvInput($_SERVER['argv']);

$success = true;

foreach ($validApp[$group] as $app) {

    $process = new Process(sprintf("./app/console %s %s", $app, (string)$args), null, null, null, 0);

    $process->run(function($status, $data) use ($output) {
        $output->write($data, false, OutputInterface::OUTPUT_RAW);
    });

    $success = $success ? $process->isSuccessful() : $success;

    $output->writeln("");
}

exit($success ? 0 : 1);

