#!/usr/bin/env php
<?php

require_once __DIR__.'/apps/bootstrap.php.cache';
require_once __DIR__.'/apps/BaseKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

// retrieve the application name
$input = new ArgvInput($_SERVER['argv']);
$output = new ConsoleOutput();

if (count($_SERVER['argv']) < 2) {

    $output->writeln(<<<ERROR
<error>Error : please provide a valid application name</error>

./sonata <application_name> <symfony:command> <command_options>

ERROR
);

   exit(1);
}

// retrieve the application name
$name = $_SERVER['argv'][1];
unset($_SERVER['argv'][1]);

$input = new ArgvInput($_SERVER['argv']);

$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';


$kernelClass = ucfirst($name).'Kernel';

include_once __DIR__.'/apps/'.ucfirst($name).'/'.$kernelClass.'.php';

$kernel = new $kernelClass($env, $debug);

$output->writeln("<info>Starting $kernelClass</info> - <comment>The Sonata Project</comment>");
$output->writeln("");

$application = new Application($kernel);
$application->setAutoExit(false);

exit($application->run($input, $output));
