sonata_basket:
    builder:            sonata.basket.builder.standard
    factory:            sonata.basket.session.factory
    loader:             sonata.basket.loader.standard


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataBasketBundle: ~
                    SonataBasketBundle: ~