_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

# FixMe
#_configurator:
#    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
#    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

sonata_payment_debug:
    resource: "@SonataPaymentBundle/Resources/config/routing/payment_debug.xml"
    prefix:   /shop/payment/debug
