# yamllint disable rule:braces
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix: /admin/resetting

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /page

sonata_media_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_customer:
    resource: '@SonataCustomerBundle/Resources/config/routing/customer.xml'
    prefix: /shop/user

sonata_basket:
    resource: '@SonataBasketBundle/Resources/config/routing/basket.xml'
    prefix: /shop/basket

sonata_order:
    resource: '@SonataOrderBundle/Resources/config/routing/order.xml'
    prefix: /shop/user/order

sonata_product_catalog:
    resource: '@SonataProductBundle/Resources/config/routing/catalog.xml'
    prefix: /shop/catalog

sonata_product:
    resource: '@SonataProductBundle/Resources/config/routing/product.xml'
    prefix: /shop/product

sonata_payment:
    resource: '@SonataPaymentBundle/Resources/config/routing/payment.xml'
    prefix: /shop/payment

sonata_invoice:
    resource: '@SonataInvoiceBundle/Resources/config/routing/invoice.xml'
    prefix: /shop/user/invoice

blog:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /blog

fos_comment:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comments
    defaults: { _format: html }
