parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_name:     sandbox
    database_user:     root
    database_password: ~

    mailer_transport:   smtp
    mailer_host:        localhost
    mailer_user:
    mailer_password:

    locale:             en

    secret:             ThisTokenIsNotSoSecretChangeIt

    # Sonata Admin Options
    sonata_admin.title:             Sonata Project
    sonata_admin.logo_title:        /bundles/sonataadmin/logo_title.png

    # Sonata News Options
    sonata_news.blog_title:         My Awesome Blog
    sonata_news.blog_link:          http://awesome-blog.ltd
    sonata_news.blog_description:   My Awesome blog description
    sonata_news.salt:               ThisTokenIsNotSoSecretChangeIt
    sonata_news.comment.emails:     [mail@example.org]
    sonata_news.comment.email_from: no-reply@example.org

    # Sonata Media options
    sonata_media.cdn.host:          /uploads/media

    # Sonata User Options
    sonata_user.google_authenticator.server:  demo.sonata-project.org

