# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataInvoiceBundle: ~
                    SonataInvoiceBundle: ~
