parameters:
    locale: en
    sonata_admin.title: 'Sonata Project'
    sonata_admin.logo_title: /bundles/sonataadmin/logo_title.png
    sonata_news.blog_title: 'My Awesome Blog'
    sonata_news.blog_link: 'http://awesome-blog.ltd'
    sonata_news.blog_description: 'My Awesome blog description'
    sonata_news.salt: ThisTokenIsNotSoSecretChangeIt
    sonata_news.comment.emails:
        - mail@example.org
    sonata_news.comment.email_from: no-reply@example.org
    sonata_media.cdn.host: '/uploads/media/'
    sonata_user.google_authenticator.server: demo.sonata-project.org
    sonata_page.varnish.command: 'if [ ! -r "/etc/varnish/secret" ]; then echo "VALID ERROR :/"; else varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"; fi;'
    sonata.fixtures.product.fake: 500
    sonata.fixtures.customer.fake: 10
    sonata.fixtures.page.create_subsite: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{App,DependencyInjection,Entity,Migrations,Sonata,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
