#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/BaseKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

// retrieve the application name
$input = new ArgvInput($_SERVER['argv']);
$output = new ConsoleOutput();

$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

include_once __DIR__.'/admin/AdminKernel.php';

$kernel = new AdminKernel($env, $debug);

$application = new Application($kernel);
$application->setAutoExit(false);

$output->writeln("<info>Starting AdminKernel</info> - <comment>The Sonata Project</comment>");
$output->writeln("");

exit($application->run($input, $output));
